# Gemns Device Management Dashboard
# Add this to your Lovelace dashboard

title: Gemns Device Management
views:
  - title: Devices
    path: devices
    type: custom:grid-layout
    badges: []
    cards:
      # Header Card
      - type: custom:button-card
        name: Gemns Status
        entity: binary_sensor.gems_ble_connected
        layout: vertical
        size: 25%
        state:
          - value: "on"
            color: "#00ff00"
            name: "BLE Connected"
          - value: "off"
            color: "#ff0000"
            name: "BLE Disconnected"
        styles:
          card:
            - height: 80px
            - background-color: "#1a1a1a"
            - border-radius: 10px
            - padding: 10px
            - margin: 5px
        custom_fields:
          ble_status: >
            [[[ return states['binary_sensor.gems_ble_connected'].state === 'on' ? '✅ BLE Connected' : '❌ BLE Disconnected' ]]]

      # Zigbee Status Card
      - type: custom:button-card
        name: Zigbee Status
        entity: binary_sensor.gems_zigbee_connected
        layout: vertical
        size: 25%
        state:
          - value: "on"
            color: "#00ff00"
            name: "Zigbee Connected"
          - value: "off"
            color: "#ff0000"
            name: "Zigbee Disconnected"
        styles:
          card:
            - height: 80px
            - background-color: "#1a1a1a"
            - border-radius: 10px
            - padding: 10px
            - margin: 5px
        custom_fields:
          zigbee_status: >
            [[[ return states['binary_sensor.gems_zigbee_connected'].state === 'on' ? '✅ Zigbee Connected' : '❌ Zigbee Disconnected' ]]]

      # Add Device Button
      - type: custom:button-card
        name: Add New Device
        icon: mdi:plus-circle
        size: 25%
        tap_action:
          action: call-service
          service: gems.add_device
          service_data:
            device_id: "test_device_001"
            device_type: "ble"
            category: "sensor"
            name: "Test Device"
            ble_discovery_mode: "v0_manual"
        styles:
          card:
            - height: 80px
            - background-color: "#2196F3"
            - border-radius: 10px
            - padding: 10px
            - margin: 5px
            - color: white
        custom_fields:
          add_text: "➕ Add Device"

      # Scan Devices Button
      - type: custom:button-card
        name: Scan for Devices
        icon: mdi:magnify
        size: 25%
        tap_action:
          action: call-service
          service: gems.scan_devices
        styles:
          card:
            - height: 80px
            - background-color: "#4CAF50"
            - border-radius: 10px
            - padding: 10px
            - margin: 5px
            - color: white
        custom_fields:
          scan_text: "🔍 Scan Devices"

      # Device List
      - type: entities
        title: Connected Devices
        entities:
          - entity: sensor.gems_test_ble_leak_sensor
            name: "Test BLE Leak Sensor"
          - entity: light.gems_test_zigbee_light_switch
            name: "Test Zigbee Light Switch"
          - entity: sensor.gems_test_ble_temperature
            name: "Test BLE Temperature Sensor"
        show_header_toggle: false
        state_color: true

      # BLE Toggle
      - type: custom:button-card
        name: BLE Toggle
        entity: input_boolean.gems_ble_enabled
        size: 50%
        tap_action:
          action: call-service
          service: gems.toggle_ble
          service_data:
            enabled: >
              [[[ return states['input_boolean.gems_ble_enabled'].state === 'off' ]]]
        styles:
          card:
            - height: 60px
            - background-color: "#1a1a1a"
            - border-radius: 10px
            - padding: 10px
            - margin: 5px
        custom_fields:
          ble_toggle: >
            [[[ return states['input_boolean.gems_ble_enabled'].state === 'on' ? '🔄 Disable BLE' : '🔄 Enable BLE' ]]]

      # Zigbee Toggle
      - type: custom:button-card
        name: Zigbee Toggle
        entity: input_boolean.gems_zigbee_enabled
        size: 50%
        tap_action:
          action: call-service
          service: gems.toggle_zigbee
          service_data:
            enabled: >
              [[[ return states['input_boolean.gems_zigbee_enabled'].state === 'off' ]]]
        styles:
          card:
            - height: 60px
            - background-color: "#1a1a1a"
            - border-radius: 10px
            - padding: 10px
            - margin: 5px
        custom_fields:
          zigbee_toggle: >
            [[[ return states['input_boolean.gems_zigbee_enabled'].state === 'on' ? '🔄 Disable Zigbee' : '🔄 Enable Zigbee' ]]]

      # Manual Device Entry Form
      - type: custom:hui-element
        card_type: form
        title: "Add Device Manually"
        submit_caption: "Add Device"
        fields:
          - name: device_id
            selector:
              text:
                placeholder: "Enter device ID (e.g., ble_sensor_001)"
          - name: device_type
            selector:
              select:
                options:
                  - label: "Bluetooth (BLE)"
                    value: "ble"
                  - label: "Zigbee"
                    value: "zigbee"
          - name: category
            selector:
              select:
                options:
                  - label: "Sensor"
                    value: "sensor"
                  - label: "Switch"
                    value: "switch"
                  - label: "Light"
                    value: "light"
                  - label: "Door"
                    value: "door"
                  - label: "Toggle"
                    value: "toggle"
          - name: name
            selector:
              text:
                placeholder: "Friendly name (optional)"
          - name: ble_discovery_mode
            selector:
              select:
                options:
                  - label: "V0 Manual Entry"
                    value: "v0_manual"
                  - label: "V1 Auto Pairing"
                    value: "v1_auto"
        submit_action:
          action: call-service
          service: gems.add_device

